apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sjl-parks-prod
objects:
# Role binding
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: default_view
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: default
  userNames:
  - system:serviceaccount:sjl-parks-dev:default
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongodb
  spec:
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    creationTimestamp: null
    labels:
      name: mongodb
    name: mongodb-internal
  spec:
    clusterIP: None
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: "mongodb"
  spec:
    serviceName: "mongodb-internal"
    replicas: 3
    selector:
      matchLabels:
        name: mongodb
    template:
      metadata:
        labels:
          name: "mongodb"
      spec:
        containers:
          - name: mongo-container
            image: "registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest"
            ports:
              - containerPort: 27017
            args:
              - "run-mongod-replication"
            volumeMounts:
              - name: mongo-data
                mountPath: "/var/lib/mongodb/data"
            env:
              - name: MONGODB_DATABASE
                value: "parks"
              - name: MONGODB_USER
                value: "mongodb"
              - name: MONGODB_PASSWORD
                value: "mongodb"
              - name: MONGODB_ADMIN_PASSWORD
                value: "mongodb_admin_password"
              - name: MONGODB_REPLICA_NAME
                value: "rs0"
              - name: MONGODB_KEYFILE_VALUE
                value: "12345678901234567890"
              - name: MONGODB_SERVICE_NAME
                value: "mongodb-internal"
            readinessProbe:
              exec:
                command:
                  - stat
                  - /tmp/initialized
    volumeClaimTemplates:
      - metadata:
          name: mongo-data
          labels:
            name: "mongodb"
        spec:
          accessModes: [ ReadWriteOnce ]
          resources:
            requests:
              storage: "4Gi"
#Role binding
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: system_image-puller
    namespace: sjl-parks-dev
  roleRef:
    name: system:image-puller
  subjects:
  - kind: ServiceAccount
    name: default
  userNames:
  - system:system:serviceaccount:sjl-parks-prod:default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: 'system:image-pullers'
    namespace: sjl-parks-dev
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: 'system:image-puller'
  subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: 'system:serviceaccounts:sjl-parks-prod'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: sjl-parks-prod
    name: system_image-puller
    namespace: sjl-parks-prod
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: 'system:image-puller'
  subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: User
      name: 'system:system:serviceaccount:sjl-parks-prod:default'
